version: '3.9'

services:
  postgres:
    image: postgres:17
    container_name: mentorlink-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mentorlink
    volumes:
      - ./docker/data/postgres:/var/lib/postgresql/data